  webserver_hostname: 'cga.vlad'
  webserver_hostname_alias: 'www.{{ webserver_hostname }}'

# Components
  pimpmylog_install: true
#  varnish_install: true

# Vagrantfile configuration
  boxipaddress: "192.168.100.104"
  boxname: "cga"
  host_synced_folder: "../docroot"
  aux_synced_folder: "../vlad_aux"
  synced_folder_type: "rsync"
#  http_port: 8080
#  varnish_http_port: 80

# MySQL Settings
  mysql_port: 3306
  mysql_root_password: sdfds87643y5thgfd
  dbname: cga
  dbuser: cga
  dbpass: sdfgdse3cvlada

# SSH Settings
  use_host_id: true
  
# SOLR Settings
  solr_install: true
